### ISSUE TITLE
メニューと価格のデータは、プログラムファイルと別にしておきたい

### ISSUE THREAD

**Issue by gomazarashi** [tdtiger/SchoolCafeteriaGacha#1]
JSONかCSVのどっちかの形で保存しておき、そのファイルを読み込む形式にするほうが良さそう

**Comment by tdtiger** [comment]
わかる

**Comment by gomazarashi** [comment]
できそうだったらやってみます

**Comment by gomazarashi** [comment]
#2 やってみたけどこれCSV(エクセルみたいな感じのやつ)のほうが良かったかも

**Comment by gomazarashi** [comment]
#3 
やってみました。データの読み込み元が変わっただけで挙動は変わっていないはず。
