### ISSUE TITLE
文字列上限

### ISSUE THREAD

**Issue by tdtiger** [tdtiger/SchoolCafeteriaGacha#9]
本文が140字を超えるときはどうしようね
商品のとこ全カットする仕様に一回したけどやめた
最初の何品かだけとかにしたほうがいいのか

**Comment by gomazarashi** [comment]
昔似たようなことをやった記憶があるので、ちょっと調整してみます

**Comment by tdtiger** [comment]
文字列上限ではなく文字数上限だったのでは．．．？と今更ながら
